### ISSUE TITLE
请问这门课会推出视频讲解或者更进一步的讲解嘛，是否已经迭代完毕？谢谢！

### ISSUE THREAD

**Issue by sanbuphy** [vesuppi/nanoPyC#1]
感觉这个循序渐进的想法很棒，但就是感觉不能完全领略到精妙之处，要是可以联系一些资料就好了

**Comment by LukeLIN-web** [comment]
> 感觉这个循序渐进的想法很棒，但就是感觉不能完全领略到精妙之处，要是可以联系一些资料就好了

写了一个适合入门的小型Python编译器项目 - 陈清扬的文章 - 知乎
https://zhuanlan.zhihu.com/p/603352525

**Comment by sanbuphy** [comment]
> > 感觉这个循序渐进的想法很棒，但就是感觉不能完全领略到精妙之处，要是可以联系一些资料就好了
> 
> 写了一个适合入门的小型Python编译器项目 - 陈清扬的文章 - 知乎 https://zhuanlan.zhihu.com/p/603352525

好的谢谢，我已经发给我的朋友，一起研究学习。

**Comment by tongzhou80** [comment]
还没有迭代完毕呢，视频讲解或者进一步的讲解之后再看看应该怎么弄，最近比较忙，不太有时间，不好意思。可能之后先不定期地更一更，对代码有任何问题的话可以先在这里开issue留言，谢谢了！

**Comment by sanbuphy** [comment]
> 
感谢付出，明白了。
